require 'rspec/core/rake_task'

namespace :spec do
  desc 'Run the functional suite against the CLI'
  RSpec::Core::RakeTask.new(:functional)

  desc 'Run the unit test cases against the CLI'
  RSpec::Core::RakeTask.new(:unit) do |t|
    t.rspec_opts = '--tag unit'
  end
end
